googlemaps.api.url=https://weather.googleapis.com/v1
googlemaps.api.key=AIzaSyDOplezwYPbdKUmZ2JffgcZ8HtMSCniexg

spring.docker.compose.lifecycle-management=start_only

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG